// This file is auto-generated by scripts/build-automation-catalog.mjs.
// Do not edit it manually. To update it after changing automations/catalog/*/manifest.json,
// run: npm run build:automations

import entry0 from "./catalog/github-pr-reviewer/manifest.json" with { type: "json" };
import entry1 from "./catalog/custom-automation/manifest.json" with { type: "json" };
import entry2 from "./catalog/github-repo-monitor/manifest.json" with { type: "json" };
import entry3 from "./catalog/github-issue-to-pr/manifest.json" with { type: "json" };
import entry4 from "./catalog/slack-standup-digest/manifest.json" with { type: "json" };
import entry5 from "./catalog/slack-channel-monitor/manifest.json" with { type: "json" };
import entry6 from "./catalog/linear-triage-assistant/manifest.json" with { type: "json" };
import entry7 from "./catalog/linear-issue-to-github-pr/manifest.json" with { type: "json" };
import entry8 from "./catalog/gitlab-issue-to-mr/manifest.json" with { type: "json" };
import entry9 from "./catalog/linear-issue-to-gitlab-mr/manifest.json" with { type: "json" };
import entry10 from "./catalog/linear-issue-to-bitbucket-pr/manifest.json" with { type: "json" };
import entry11 from "./catalog/jira-issue-to-pr/manifest.json" with { type: "json" };
import entry12 from "./catalog/qa-changes/manifest.json" with { type: "json" };
import entry13 from "./catalog/jira-issue-to-gitlab-mr/manifest.json" with { type: "json" };
import entry14 from "./catalog/research-brief-writer/manifest.json" with { type: "json" };
import entry15 from "./catalog/jira-issue-to-bitbucket-pr/manifest.json" with { type: "json" };
import entry16 from "./catalog/github-agents-md-maintainer/manifest.json" with { type: "json" };
import entry17 from "./catalog/github-delivery-watchdog/manifest.json" with { type: "json" };
import entry18 from "./catalog/github-issue-triage/manifest.json" with { type: "json" };
import entry19 from "./catalog/upstream-fork-sync/manifest.json" with { type: "json" };
import entry20 from "./catalog/incident-retrospective-drafter/manifest.json" with { type: "json" };
import entry21 from "./catalog/news-digest/manifest.json" with { type: "json" };
import entry22 from "./catalog/github-stale-ci-pr-closer/manifest.json" with { type: "json" };

export const AUTOMATION_CATALOG_ENTRIES = [
  entry0,
  entry1,
  entry2,
  entry3,
  entry4,
  entry5,
  entry6,
  entry7,
  entry8,
  entry9,
  entry10,
  entry11,
  entry12,
  entry13,
  entry14,
  entry15,
  entry16,
  entry17,
  entry18,
  entry19,
  entry20,
  entry21,
  entry22,
];
